// Seed data for custom order configurator
// Based on the "Design Your Own Piece" wireframe

export const productTypesData = [
  {
    name: 'Blanket',
    slug: 'blanket',
    icon: 'home',
    description: 'Cozy custom blankets in any size',
    basePrice: 85,
    priceRange: { min: 85, max: 150 },
    estimatedTimeline: '2-3 weeks',
    status: 'active',
    order: 1,
  },
  {
    name: 'Sweater',
    slug: 'sweater',
    icon: 'shirt',
    description: 'Hand-crafted sweaters tailored to your style',
    basePrice: 120,
    priceRange: { min: 120, max: 200 },
    estimatedTimeline: '3-4 weeks',
    status: 'active',
    order: 2,
  },
  {
    name: 'Bag',
    slug: 'bag',
    icon: 'bag',
    description: 'Custom bags and purses',
    basePrice: 45,
    priceRange: { min: 45, max: 90 },
    estimatedTimeline: '1-2 weeks',
    status: 'active',
    order: 3,
  },
  {
    name: 'Scarf',
    slug: 'scarf',
    icon: 'user',
    description: 'Warm and stylish scarves',
    basePrice: 35,
    priceRange: { min: 35, max: 65 },
    estimatedTimeline: '1-2 weeks',
    status: 'active',
    order: 4,
  },
  {
    name: 'Hat',
    slug: 'hat',
    icon: 'hat',
    description: 'Custom hats and beanies',
    basePrice: 25,
    priceRange: { min: 25, max: 50 },
    estimatedTimeline: '1 week',
    status: 'active',
    order: 5,
  },
  {
    name: 'Baby Set',
    slug: 'baby-set',
    icon: 'heart',
    description: 'Adorable baby sets and accessories',
    basePrice: 60,
    priceRange: { min: 60, max: 110 },
    estimatedTimeline: '2-3 weeks',
    status: 'active',
    order: 6,
  },
]

export const customColorsData = [
  {
    name: 'Cream',
    slug: 'cream',
    hexCode: '#F5E6D3',
    colorFamily: 'neutral',
    status: 'active',
    order: 1,
  },
  {
    name: 'Sage Green',
    slug: 'sage-green',
    hexCode: '#9CAF88',
    colorFamily: 'cool',
    status: 'active',
    order: 2,
  },
  {
    name: 'Dusty Rose',
    slug: 'dusty-rose',
    hexCode: '#D4A5A5',
    colorFamily: 'pastel',
    status: 'active',
    order: 3,
  },
  {
    name: 'Navy Blue',
    slug: 'navy-blue',
    hexCode: '#2C3E50',
    colorFamily: 'cool',
    status: 'active',
    order: 4,
  },
  {
    name: 'Terracotta',
    slug: 'terracotta',
    hexCode: '#C97064',
    colorFamily: 'warm',
    status: 'active',
    order: 5,
  },
  {
    name: 'Charcoal',
    slug: 'charcoal',
    hexCode: '#4A4A4A',
    colorFamily: 'neutral',
    status: 'active',
    order: 6,
  },
]

export const yarnTypesData = [
  {
    name: 'Organic Cotton',
    slug: 'organic-cotton',
    description: 'Soft, breathable, machine washable',
    properties: [
      { property: 'Soft' },
      { property: 'Breathable' },
      { property: 'Machine washable' },
      { property: 'Hypoallergenic' },
    ],
    priceModifier: 0,
    priceModifierType: 'fixed',
    weight: 'worsted',
    composition: '100% Organic Cotton',
    careInstructions: 'Machine wash cold, tumble dry low',
    status: 'active',
    order: 1,
  },
  {
    name: 'Merino Wool',
    slug: 'merino-wool',
    description: 'Warm, luxurious, naturally antibacterial',
    properties: [
      { property: 'Warm' },
      { property: 'Luxurious' },
      { property: 'Naturally antibacterial' },
      { property: 'Temperature regulating' },
    ],
    priceModifier: 20,
    priceModifierType: 'fixed',
    weight: 'dk',
    composition: '100% Merino Wool',
    careInstructions: 'Hand wash cold, lay flat to dry',
    status: 'active',
    order: 2,
  },
  {
    name: 'Bamboo Blend',
    slug: 'bamboo-blend',
    description: 'Eco-friendly, silky smooth, hypoallergenic',
    properties: [
      { property: 'Eco-friendly' },
      { property: 'Silky smooth' },
      { property: 'Hypoallergenic' },
      { property: 'Moisture-wicking' },
    ],
    priceModifier: 15,
    priceModifierType: 'fixed',
    weight: 'sport',
    composition: '70% Bamboo, 30% Cotton',
    careInstructions: 'Machine wash gentle, lay flat to dry',
    status: 'active',
    order: 3,
  },
  {
    name: 'Alpaca Wool',
    slug: 'alpaca-wool',
    description: 'Ultra-soft, lightweight, temperature regulating',
    properties: [
      { property: 'Ultra-soft' },
      { property: 'Lightweight' },
      { property: 'Temperature regulating' },
      { property: 'Durable' },
    ],
    priceModifier: 35,
    priceModifierType: 'fixed',
    weight: 'bulky',
    composition: '100% Alpaca',
    careInstructions: 'Hand wash cold, lay flat to dry',
    status: 'active',
    order: 4,
  },
]
